<!-- 
/**
 * TDProject_Project
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */
-->

<script type="text/javascript">
<!--

/**
 * Loads the estimation for task with the passed ID and replaces the HTML 
 * of the div containers with the id #estimation with the form to edit the 
 * requested estimation.
 *
 * @param int taskId The ID of the task to load the estimation for
 * @return boolean
 */
function loadEstimation(taskId) {

	$.ajax({
	    type: "GET",
	    url: "?path=/estimation&taskIdFk=" + taskId,
	    success: function(data) {
	        $('#estimation').html(data);
	    }
    });
    
	return false;
}

//-->
</script>

<div id="estimation"></div>