<?php

/**
 * TDProject_Project
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

$tasks = array();

foreach ($this->getLoggings() as $logging) {

    $taskId = $logging->getTask()->getTaskId()->intValue();
    $userId = $logging->getUser()->getUserId()->intValue();

    $min = $this->calculateMinutes($logging->getFrom(), $logging->getUntil());

    if (array_key_exists($taskId, $tasks)) {
        $users = $tasks[$taskId];
    } else {
        $users = array();
    }

    if (array_key_exists($userId, $users)) {
        $minutes = $users[$userId];
    } else {
        $minutes = 0;
    }

    $minutes += $min;

    $tasks[$taskId][$userId] = $minutes;
}

?>

<div>
	<ul><?php foreach ($tasks as $taskId => $task) { ?>
		<li>
		    <?php echo $taskId ?>
		    <ul><?php foreach($task as $userId => $minutes) { ?>
		    	<li><?php echo $userId ?> -  <?php echo $minutes ?></li>
		    <?php } ?></ul>
		</li>
	<?php } ?></ul>
</div>

<!-- table width="100%">
	<thead>
		<tr align="left">
    		<th>Id</th>
    		<th>Projekt</th>
    		<th>Task</th>
    		<th>User</th>
    		<th>von</th>
    		<th>bis</th>
    		<th>min</th>
		</tr>
	</thead>
	<tbody><?php if ($this->getLoggings()->size() > 0 ) { ?>
		<?php foreach ($this->getLoggings() as $logging) { ?><tr align="left">
    		<td><?php echo $logging->getTaskUserId() ?></td>
    		<td><?php echo $logging->getProject()->getName() ?></td>
    		<td><?php echo $logging->getTask()->getName() ?></td>
            <td><?php echo $logging->getUser()->getUsername() ?></td>
    		<td><?php echo $this->toDate($logging->getFrom()) ?></td>
    		<td><?php echo $this->toDate($logging->getUntil()) ?></td>
            <td><?php echo $this->calculateMinutes($logging->getFrom(), $logging->getUntil()) ?></td>
	    </tr><?php } ?>
	    <?php } else { ?><tr>
	    	<td colspan="6">Für diesen Task sind bisher keine Buchungen vorhanden!</td>
	    </tr><?php } ?>
    </tbody>
    <tfoot>
    	<tr align="left">
    		<th></th>
    		<th></th>
    		<th></th>
    		<th></th>
    		<th></th>
    		<th></th>
    		<th></th>
    	</tr>
    </tfoot>
</table -->