<?php
 
/**
 * TDProject_Project
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

// load the data from the Request and render it JSON encoded
echo $this->getRequest()
    ->getAttribute(TDProject_Project_Controller_Util_WebRequestKeys::JSON_RESULT)
    ->toJson();

?>