<!-- 
/**
 * TDProject_Project
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */
-->

<script type="text/javascript">
<!--

$(function() {

	$.ajax({
	    type: "GET",
	    url: "?namespace=TDProject&module=Project&path=/logging/widget&method=create",
	    success: function(data) {
	        $('#logging').html(data);
	    }
    });
    
	return false;
});

//-->
</script>

<div id="logging"></div>