<?php
/**
 * TDProject_Project
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

if (!$this->getProjectId()->equals(new TechDivision_Lang_Integer(0))) { ?>

<div id="estimations" class="estimations"></div>

<?php $this->_getChildHtml('estimation') ?>

<script type="text/javascript">
<!--
$(function () {
	$("#estimations")
    	// initialize the TreeView and the plugins
    	.jstree({
    		"json_data" : {
    			"ajax" : {
    				"url" : "?path=/task/json/project",
    				"data" : function (n) {
    					return { id : n.attr ? n.attr("id") : <?php echo $this->getProjectId() ?> };
    				},
    				"success" : function (data) {
        				return data.d;
        			},
    				"failure" : function (data) {
        				return data.d;
        			}
    			}
    		},
    		"plugins" : [ "json_data", "ui", "themeroller" ]
    	})
		// load the estimation if a node is selected
		.bind('select_node.jstree', function(e, data) {
			loadEstimation(
				data.rslt.obj.attr("id").replace("task_", "")
			);
        });
});
//-->
</script>
<?php } ?>