<?php
 
/**
 * TDProject_Project
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

?>
<script type="text/javascript">
<!--

/**
 * Loads the task with the passed ID and replaces the HTML of the div 
 * containers with the id #task with the form to edit the requested task.
 *
 * @param int taskId The ID of the task to edit
 * @return boolean
 */
function loadTask(taskId) {

	$.ajax({
	    type: "GET",
	    url: "?path=/task&method=edit&taskId=" + taskId,
	    success: function(data) {
	        $('#task').html(data);
	    }
    });
    
	return false;
}

//-->
</script>

<div id="task"></div>