<?php

/**
 * TDProject_Project
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

?>
<script type="text/javascript">
<!--

$(function() {

	// initialize the description for the selected task
	loadDescription($('#<?php echo $this->getBlockName() ?> :selected').val());

	// listener when the selected task changes
	$('#<?php echo $this->getBlockName() ?>').change(function() {
		loadDescription($('#<?php echo $this->getBlockName() ?> :selected').val(), 0);
	});

	return false;
});

/**
 * Loads the description for the task with the passed ID.
 *
 * @param taskId The ID of the task to load the description for
 * @return void
 */
function loadDescription(taskId) {

	$.ajax({
	    type: "GET",
	    url: "?path=/logging/task",
	    data: "method=loadDescription&taskId=" + taskId,
	    success: function(data) {
	        $('#description').html(data);
    	}
	});

	return false;
}

//-->
</script>
<label for="<?php echo $this->getBlockName() ?>" class="type-text">
	<span class="title"><?php echo $this->translate('logging.view.label.task') ?>: </span>&nbsp;<span class="required">*</span>
	<select name="<?php echo $this->getBlockName() ?>" id="<?php echo $this->getBlockName() ?>">
		<options><?php foreach ($this->getTasks() as $task) { ?>
			<?php $this->_getChildHtml($task->getTaskId()->intValue()); ?>
		<?php } ?></options>
	</select>
	<div id="description"></div>
</label>