<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title><?php echo $this->getSubject() ?></title>
	</head>
	<body>
		<p>
			Es wurde versucht, einen Task, über den maximalen Schätzwert hinaus, zu überbuchen!
		</p>
		<p>
			Folgend Detaildaten liegen vor:
			<ul>
				<li>Benutzer: <a href="mailto:<?php echo $this->getUser()->getEmail() ?>"><?php echo $this->getUser()->getUsername() ?></a></li>
				<li>Projekt: <?php echo $this->getProject()->getName() ?></li>
				<li>Task: <?php echo $this->getTask()->getName() ?></li>
				<li>Tätigkeitsbeschreibung: <?php echo $this->getTaskUser()->getDescription() ?></li>
				<li>Von: <?php echo $this->getTaskUserFrom() ?> - <?php echo $this->getTaskUserUntil() ?></li>
				<li>Aktuell gebucht: <?php echo $this->asHours($this->getTotalBefore()) ?></li>
				<li>Danach gebucht (theoretisch): <?php echo $this->asHours($this->getTotal()) ?></li>
				<li>Maximal buchbar: <?php echo $this->asHours($this->getMaximum()) ?></li>
			</ul>
		</p>
		<p>
			Bitte kontaktieren Sie den Benutzer. Es bestehen folgende Möglichkeiten:
			<ul>
				<li>Der Benutzer hat irrtümlich versucht auf diesen Task zu buchen, die korrekte Buchung ist bereits erfolgt</li>
				<li>Sie legen einen zusätzlichen Task an, um dem Benutzer das Buchen zu ermöglichen</li>
			</ul>
		</p>
		<p>
			TDProject<br/>
			System Services
		</p>
	</body>
</html>