<?php

/**
 * TDProject_Project
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

?>
<ul>
	<li>
		<?php echo $this->getTask()->getName() ?> (<?php echo $this->getTotal() ?> h)
		<ul><?php foreach ($this->getLoggings() as $logging) { ?>
			<li>
    		    <?php echo $logging->getUsername() ?> - <?php echo $this->getHours($logging) ?>
    		</li>
		<?php } ?></ul>
	    <?php foreach ($this->_getChilds() as $child) { ?>
			<?php $this->_getChildHtml($child->getBlockName()) ?>
		<?php } ?>
	</li>
</ul>